export const AUTHENTICATED_USER = "AUTHENTICATED_USER";
export const LOGOUT = "LOGOUT";

export const SUCCESSFULLY_LOGIN = "SUCCESSFULLY_LOGIN";
export const UNSUCCESSFULLY_LOGIN = "UNSUCCESSFULLY_LOGIN";

export const SUCCESSFULLY_REGISTER = "SUCCESSFULLY_REGISTER";
export const UNSUCCESSFULLY_REGISTER = "UNSUCCESSFULLY_REGISTER";

export const SHOW_ALERT = "SHOW_ALERT";
export const CLEAN_ALERT = "CLEAN_ALERT";

export const UPLOAD_FILE = "UPLOAD_FILE";
export const SUCCESSFULLY_UPLOAD_FILE = "SUCCESSFULLY_UPLOAD_FILE";
export const UNSUCCESSFULLY_UPLOAD_FILE = "UNSUCCESSFULLY_UPLOAD_FILE";

export const SUCCESSFULLY_CREATE_LINK = "SUCCESSFULLY_CREATE_LINK";
export const UNSUCCESSFULLY_CREATE_LINK = "UNSUCCESSFULLY_CREATE_LINK";

export const CLEAN_STATE = "CLEAN_STATE";

export const ADD_PASSWORD = "ADD_PASSWORD";
export const ADD_DOWNLOADS = "ADD_DOWNLOADS";

